# Change these first
owner: DFE-Digital # Your GitHub organization or username, where this repository lives
repo: schools-commerical-team-upptime # The name of this repository

sites:
  - name: GHBS Staging
    url: https://staging-get-help-buying-for-schools.education.gov.uk/
  - name: GHBS Production
    url: https://www.get-help-buying-for-schools.service.gov.uk/
  - name: FaF Production
    url: https://find-dfe-approved-framework.service.gov.uk/find/type
  - name: FaF Production - List page
    url: https://find-dfe-approved-framework.service.gov.uk/list
#   - name: FaF Test
#     url: https://s107d01-webapp-v2-01.azurewebsites.net/find/type
#   - name: FaF Test - List page
#     url: https://s107d01-webapp-v2-01.azurewebsites.net/list


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /schools-commerical-team-upptime/
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Schools Commercial Team
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

assignees:
  - ryantk
  - EdwinKruglov
  - serenaabbott11
  - atifmir-0136
