# Change these first
owner: DFE-Digital # Your GitHub organization or username, where this repository lives
repo: schools-commerical-team-upptime # The name of this repository

sites:
  - name: GHBS Staging
    url: https://staging-get-help-buying-for-schools.education.gov.uk/
  - name: GHBS Production
    url: https://www.get-help-buying-for-schools.service.gov.uk/
  - name: FaF Production
    url: https://find-dfe-approved-framework.service.gov.uk/


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /schools-commerical-team-upptime/
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Schools Commercial Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: See uptime status across schools commercial deplyed applications.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

assignees:
  - ryantk
  - EdwinKruglov
  - serenaabbott11